runtime: python
env: flex
# api_version: 1
entrypoint: gunicorn -b :$PORT -k gevent main:app
# worker_class: 'gevent'
threadsafe: true

runtime_config:
  python_version: 3.5

handlers:
- url: /.*
  script: main.app
